name: Gitstamp for GitHub Actions
author: Arto Bendiken
description: Timestamp your Git commits using the Arweave permaweb.
inputs:
  wallet-key:
    description: The Arweave wallet key to use for signing transactions.
    required: true
outputs:
  transaction-id:
    description: The Arweave transaction ID.
  transaction-link:
    description: The Arweave transaction on ViewBlock.io.
  response-code:
    description: The Arweave HTTP API response status code.
  response-text:
    description: The Arweave HTTP API response status text.
runs:
  using: node12
  main: index.js
branding:
  icon: clock
  color: gray-dark
