---
name: Gitstamp
on: [push]
jobs:
  gitstamp:
    runs-on: ubuntu-latest
    name: Record commit on Gitstamp
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Submit Arweave transaction
        uses: ./
        with:
          wallet-key: ${{ secrets.ARWEAVE_KEYFILE }}
